version: "3.8"
services:
    mysql:
        image: kb674/fighter_db_image:latest
        container_name: mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    server:
        image: kb674/fighter_server_image:latest
        container_name: server
        ports:
            - target: 5000
              published: 5000
              protocol: tcp
        environment:
            DATABASE_URI: ${DATABASE_URI}
    two_api:
        image: kb674/fighter_two_image:latest
        container_name: service_two_api
    three_api:
        image: kb674/fighter_three_image:latest
        container_name: service_three_api
    four_api:
        image: kb674/fighter_four_image:latest
        container_name: service_four_api
